language: cpp
compiler: gcc
dist: xenial

before_install:
  # Not much
  # To do

install: 
  # C++17
  # Not now

script:
  - mkdir qemu_esp32
  - cd qemu_esp32
  - ../configure --disable-werror --prefix=`pwd`/root --target-list=xtensa-softmmu,xtensaeb-softmmu
  - make

