name: CI build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential libpixman-1-0 libpixman-1-dev libglib2.0-dev zlib1g-dev
    - name: Compile qemu
      run: |
        mkdir qemu_esp32
        cd qemu_esp32
        $GITHUB_WORKSPACE/configure --disable-werror --prefix=./root --target-list=xtensa-softmmu --python=/usr/bin/python2
        make -j 2
    - uses: actions/upload-artifact@v2
      with:
        name: qemu-system-xtensa
        path: ./qemu_esp32/xtensa-softmmu/qemu-system-xtensa

  build-mac:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Brew install
      run: |
        brew install pixman
        brew install glib
        brew install dtc
        brew install automake
        brew install pkg-config
    - name: configure
      run: |        
        mkdir qemu_esp32
        cd qemu_esp32
        $GITHUB_WORKSPACE/configure --disable-werror --disable-sdl --disable-gtk  --prefix=`pwd`/root --target-list=xtensa-softmmu
        mv version py_version
        make -j 2
